### ISSUE TITLE
Replace UUIDs with something else for session ids and mock ids

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#122]
UUIDs are too long and not really readable. Some alternatives would be more readable:

- [shortid](https://godoc.org/github.com/teris-io/shortid) with a custom alphabet (no `_` and `-`, just `[a-z0-9]` or even just `[a-z]`
- something more fun like [icrowley/fake](https://github.com/icrowley/fake)
- maybe something else

**Comment by gwleclerc** [comment]
+1 for shortIDs, if you want to add some things funny we could use fake or other generators for session names
