### ISSUE TITLE
"session not found" on mocks page when session contains a "-"

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#137]
![Capture d’écran 2020-06-29 à 15 02 16](https://user-images.githubusercontent.com/2796344/86008800-94b41500-ba19-11ea-874f-074d6218fb4e.png)

I guess the %2B in the url is a -

**Comment by gwleclerc** [comment]
`%2B` is the code for a `+` that's why I removed the + from the alphabet in [this commit](https://github.com/Thiht/smocker/commit/cb2c7eabbd6a3a9b40d9edf18140544f1f86f040#diff-7ddfb3e035b42cd70649cc33393fe32c) but we didn't release Smocker since

**Comment by gwleclerc** [comment]
Should be fixed in https://github.com/Thiht/smocker/releases/tag/0.13.0

**Comment by Thiht** [comment]
Nice 😁
