### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Thiht** [Thiht/smocker#16]
This one is cool, and under CC BY License [Smocker](https://thenounproject.com/jaremfrye/icon/413125/)

**Comment by mandyellow** [comment]
Hello! 🦊 I create a logo for your project. Hope you like it!

There are two color versions to choose.

![image](https://user-images.githubusercontent.com/30158643/66590377-4dd77400-eb99-11e9-87d4-5e53b8cecd85.png)

**Comment by marcaudefroy** [comment]
Nice! Thanks you very much @mandyellow! :)

**Comment by matcornic** [comment]
Many thanks @mandyellow ! Open Source is surprising sometimes :)

Btw, both are great. I would vote for the red one though.

**Comment by Thiht** [comment]
@mandyellow Thank you, this is awesome :) I love the red one!

I suggest you add the logo in docs/logo.png and docs/logo.svg (or whichever format you used and are ready to share). I'd also appreciate if you could add a `docs/LICENSE` file next to the logo, describing the license you wish to release the logo to. If you're not familiar with licensing, I suggest you use one of the Creative Commons licenses, which are particularly fit for artistic work: https://creativecommons.org/choose/?lang=en

For the record, can you tell us how you find this repo? :)

**Comment by mandyellow** [comment]
You're welcome guys, I'm very happy that I can help the community without coding haha

Answering the question, I found this repo searching for "logo" in "issues". One thing that helps me choose your project was the smoker icon reference (this kind of thing helps a lot starting to create).

**Comment by mandyellow** [comment]
I created the PR. Please, could you review the license? I'm new to it.

**Comment by Thiht** [comment]
Finally added to the README! thanks again @mandyellow !
