### ISSUE TITLE
Mock generator UI

### ISSUE THREAD

**Issue by michaelsogos** [Thiht/smocker#183]
Hi There,

Great tool, thanks!

Do you have plan to add an "mock generator" in order to ease YAML creation, i mean instead of an text editor (that should remain for fine tuning) why not a WEB FORM that will generate corresponding YAML?

**Comment by gwleclerc** [comment]
Hi, yes it is definitely planned but not for now. We need to 
In the meantime, I advise you to use the json schema with the YAML plugin in vscode to help you to write and syntactically validate your mocks.

You can find more details in the [tooling section](https://smocker.dev/guide/tooling.html) of the documentation

**Comment by Thiht** [comment]
Done, it will be deployed on the next release :)

There are still improvements to be made (auto-fill when using "Create mock from entry", some validations, etc.) to  the new editor but it should be a good first step!
