### ISSUE TITLE
Upgrade dependency Masterminds/sprig to v3.2+

### ISSUE THREAD

**Issue by Kiliandeca** [Thiht/smocker#211]
Hi, first of all thank you for this awesome tool, i'm trying to add some randomess in my dynamic responses. 
The `randInt` function was added to `Masterminds/sprig` in v3.2.0 but Smocker currently use v3.1.0, is it possible to upgrade this dependency and publish a new version of smocker ?

[Masterminds/sprig changelog](https://github.com/Masterminds/sprig/releases/tag/v3.2.0)

**Comment by Thiht** [comment]
Yep, I'll do that ASAP :) 

I actually followed the pull request on Sprig (https://github.com/Masterminds/sprig/pull/211#issuecomment-674387108) just for this but didn't know it's been merged, thanks for the heads up!

**Comment by Thiht** [comment]
Released in 0.16.3!
