### ISSUE TITLE
Url encoded path params are not preserved

### ISSUE THREAD

**Issue by andrcuns** [Thiht/smocker#232]
Hi,

Great project! Found it to be quite useful but encountered an issue.

It seems that url encoded path parameters are not preserved when proxied. By the looks of it, path is always decoded and then left like that.

My endpoint would be calling something like "/api/v4/projects/encoded%2Fpath" but the proxy would then call "/api/v4/projects/encoded/path" which will yield in 404 since api path like that doesn't exist.

**Comment by Thiht** [comment]
Thanks for the report, this will be fixed in the next release :)

**Comment by andrcuns** [comment]
Thanks for such a quick fix 🎉
