### ISSUE TITLE
Updated Docker Image

### ISSUE THREAD

**Issue by alexilievski** [Thiht/smocker#260]
The current Docker image [0.18.2](https://hub.docker.com/layers/smocker/thiht/smocker/0.18.2/images/sha256-fb226e6bce97161bcd78cc18f1dbfeecb0a8e30ae2d605bfe09e852e73282600?context=explore) includes a version of Go that has vulnerabilities reported.

Is it possible to release a new build of the image with the latest Go patch updates included?

**Comment by gwleclerc** [comment]
The latest release 0.18.3 was built using golang 1.21.1 and has passed Sonar security checks.
