### ISSUE TITLE
API - Ability to clear history without resetting all and losing mocks

### ISSUE THREAD

**Issue by wz1971** [Thiht/smocker#265]
Hi, I've started to use Smocker in a docker container as my choice for mocking up REST endpoints.
Thank you very much for the wonderful work done so far.

I wanted to suggest you to add the possibility of clearing the history without using reset, as it causes the created mocks to be lost too.

Thanks and regards.

**Comment by gwleclerc** [comment]
Hi,
You can already sort of do this by locking your mocks, which will keep them in the next session
