### ISSUE TITLE
unable to set SMOCKER_CONFIG_BASE_PATH in container install

### ISSUE THREAD

**Issue by BinaryWorld2099** [Thiht/smocker#270]
I was trying to set MOCKER_CONFIG_BASE_PATH=/smocker 

docker run -d --restart=always -p 8080:8080 -p 8081:8081 -e SMOCKER_CONFIG_BASE_PATH=/smocker --name smocker thiht/smocker

result:
![image](https://user-images.githubusercontent.com/106383882/214274804-141192f3-25d9-40b2-9144-11b0dee9ff57.png)

![image](https://user-images.githubusercontent.com/106383882/214275033-878674ee-5ca1-497d-bedd-5ae99d2cc4d5.png)

**Comment by gwleclerc** [comment]
Hi, can you try to add a trailing `/` to your `SMOCKER_CONFIG_BASE_PATH` ?
I'm prettry sure that it will work with 
```
docker run -d --restart=always -p 8080:8080 -p 8081:8081 -e SMOCKER_CONFIG_BASE_PATH=/smocker/ --name smocker thiht/smocker
```

**Comment by BinaryWorld2099** [comment]
Sorry, seems still not working with trailing /

http://localhost:8081/smocker
http://localhost:8081/smocker/
http://localhost:8081/smocker/pages/mock

![image](https://user-images.githubusercontent.com/106383882/214485735-8bf918db-4bac-4da2-83ed-65deef682356.png)
![image](https://user-images.githubusercontent.com/106383882/214485789-b701e236-01be-4f81-899b-2df5b99af4d8.png)
![image](https://user-images.githubusercontent.com/106383882/214485891-4957db3a-f41b-40ce-8222-f32105841ff9.png)

**Comment by BinaryWorld2099** [comment]
In minikube and docker, only not setting SMOCKER_CONFIG_BASE_PATH was working 

![image](https://user-images.githubusercontent.com/106383882/214491661-07832c7b-7881-482d-82ce-d8abc4f32d61.png)
![image](https://user-images.githubusercontent.com/106383882/214491766-4d66adb6-7f90-49a6-9612-1ad1f38ef859.png)

**Comment by BinaryWorld2099** [comment]
I am able to deploy in K8s environment now, with custom URL
Below is my setting  
Ingress:
![image](https://user-images.githubusercontent.com/106383882/220528510-b6b87218-a105-4396-b563-9f50c266dc17.png)
![image](https://user-images.githubusercontent.com/106383882/220528770-985b6229-1caa-4045-b591-7eefb9dc44f5.png)

thanks for you help
