### ISSUE TITLE
Copy history request as curl

### ISSUE THREAD

**Issue by gwleclerc** [Thiht/smocker#88]
It could be great in the history page to be able to copy request as curl command to easily reproduce calls

**Comment by Thiht** [comment]
Allez je suis deter aujourd'hui, je fais ça :D

**Comment by gwleclerc** [comment]
Profites en pour review la #72 aussi histoire de voir si je m'acharne à faire un truc propre en svg ou si on trash

**Comment by Thiht** [comment]
nan on trash pas on garde, mais j'ai pas réussi à lancer en local, c'est pour ça que j'ai pas encore merge x)
le mieux ce sera de review ensemble quand tu reviendras je pense ! (après si t'es confiant on peut merge, sur le code ça me va)
